version: '3.8'

services:
  api:
    build: 
      context: .          
      dockerfile: Dockerfile.api   
    container_name: compiler-api
    restart: always
    ports:
      - "8000:8000"  
    environment:
      - PORT=8000
      - MONGO_URI=${MONGO_URI}
      - MY_COMPILER_SECRET=${MY_COMPILER_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GOOGLE_GEMINI_API=${GOOGLE_GEMINI_API}
      - GENAI_MODEL=${GENAI_MODEL}
    volumes:
      - ./temp:/app/temp
    depends_on:
      - redis

  worker:
    build: 
      context: .       
      dockerfile: Dockerfile.worker 
    container_name: compiler-worker
    restart: always
    command: npm run start:worker
    environment:
      - MONGO_URI=${MONGO_URI}
      - GOOGLE_GEMINI_API=${GOOGLE_GEMINI_API}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=${REDIS_USERNAME}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./temp:/app/temp
    depends_on:
      - redis

  redis:
    image: redis:alpine
    container_name: compiler-redis
    restart: always
