FROM node:22-slim

WORKDIR /app

# Install all compilers (Java, C++, Python)
RUN apt-get update && apt-get install -y --no-install-recommends \
    dumb-init \
    g++ \
    gcc \
    python3 \
    default-jdk-headless \
    && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json ./
RUN npm install

COPY . .


ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["npm", "run", "start:worker"]